---
apiVersion: v1
kind: Pod    
metadata:
  name: myapi   
  labels:
    name: myapi-web        
spec:
  containers:
  -
    name: myapi-web 
    image: mhausenblas/simpleservice:0.5.0 # This is the download name 
    ports:
     -
       name: web      # port name
       containerPort: 9876     # access on this port (int)
       protocol: TCP           # TCP or UDP
