apiVersion: v1  
kind: Pod  
metadata:
  name: webservice01
spec:
  containers:
  - name: webservice01-web 
    image: bchd.registry/granier-webby 
    ports:
    - name: web 
      containerPort: 8888 
      protocol: TCP 

