---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    app: myk8swebby
spec:
  selector:
    matchLabels:
      app: myk8swebby
  replicas: 3
  template:
    metadata:
      labels:
        app: myk8swebby
    spec:
      containers:
      - name: myk8swebby
        image: bchd.regisry/granier-webby
        ports:
        - containerPort: 8888
